const departments = [
    {
        code: "AAB",
        name: "ABE/School of Architecture and the Built Environment",
    },
    { code: "ADB", name: "ABE/Architecture" },
    { code: "ADC", name: "ABE/Architecture" },
    { code: "ADD", name: "ABE/Architecture" },
    { code: "ADF", name: "ABE/Lighting Design" },
    { code: "AFA", name: "ABE/Civil and Architectural Engineering" },
    { code: "AFB", name: "ABE/Building Materials" },
    { code: "AFC", name: "ABE/Building Technology" },
    { code: "AFD", name: "ABE/Building Services and Energy Systems" },
    { code: "AFE", name: "ABE/Structural Design \u0026 Bridges" },
    { code: "AFF", name: "ABE/Concrete Structures" },
    { code: "AFH", name: "ABE/Soil- and Rock Mechanics" },
    { code: "AFK", name: "ABE/Constructional Engineering and Design" },
    { code: "AFL", name: "ABE/Fluid and Climate Technology" },
    { code: "AFP", name: "ABE/Transport Planning" },
    { code: "AFT", name: "ABE/Sustainable Buildings" },
    { code: "AG", name: "ABE/Urban Planning and Environment" },
    { code: "AGB", name: "ABE/Urban and Regional Studies" },
    { code: "AGF", name: "ABE/Geoinformatics" },
    { code: "AGI", name: "ABE/Transport and Systems Analysis" },
    { code: "AIB", name: "ABE/Real Estate Economics and Finance" },
    { code: "AIC", name: "ABE/Real Estate Planning and Land Law" },
    { code: "AID", name: "ABE/Construction and Facilities Management" },
    { code: "AIE", name: "ABE/Real Estate Business and Financial Systems" },
    { code: "AIG", name: "ABE/Geodesy and Satellite Positioning" },
    { code: "AKB", name: "ABE/Philosophy" },
    { code: "AKC", name: "ABE/History of Science, Technology and Environment" },
    {
        code: "AL",
        name: "ABE/Sustainable development, environmental science and engineering",
    },
    { code: "ALF", name: "ABE/Sustainability and Environmental Engineering" },
    {
        code: "AMB",
        name: "ABE/Contract Education: Urban Development and Design",
    },
    { code: "BA", name: "BIO/Biotechnology" },
    { code: "BB", name: "BIO/Biotechnology" },
    { code: "CB", name: "CBH/School-wide" },
    { code: "CD", name: "CBH/Biomedical Engineering and Health Systems" },
    { code: "CE", name: "CBH/Chemistry" },
    { code: "CF", name: "CBH/Chemical Engineering" },
    { code: "CG", name: "CBH/Fibre and Polymer Technology" },
    { code: "CH", name: "CBH/Gene Technology" },
    { code: "CJ", name: "CBH/Protein Science" },
    { code: "CK", name: "CBH/Industrial Biotechnology" },
    { code: "CL", name: "CBH/Theoretical Chemistry and Biology" },
    { code: "CM", name: "CBH/Engineering Pedagogics" },
    { code: "DA", name: "CSC/Computer Science and Communication" },
    { code: "DAG", name: "CSC/Computer Science and Communication" },
    { code: "DD", name: "CSC/Computer Science" },
    { code: "DH", name: "CSC/Human-Computer Interaction" },
    { code: "DK", name: "CSC/computational Science and Technology" },
    { code: "DL", name: "CSC/Theoretical Computer Science" },
    { code: "DM", name: "CSC/Media Technology and Interaction Design" },
    { code: "DME", name: "CSC/Media Technology and Interaction Design" },
    { code: "DO", name: "CSC/Robotics, Perception and Learning" },
    { code: "DT", name: "CSC/Speech, Music and Hearing" },
    { code: "ED", name: "EES/Fusion Plasma Physics" },
    { code: "EF", name: "EES/Space and Plasma Physics" },
    { code: "EI", name: "EES/Electromagnetic Engineering" },
    { code: "EK", name: "EES/Micro and Nanosystems" },
    { code: "EL", name: "EES/Automatic Control" },
    { code: "EN", name: "EES/Electric Power and Energy Systems" },
    { code: "EO", name: "EES/Information Science and Engineering" },
    { code: "EP", name: "EES/Network and Systems Engineering" },
    { code: "HA", name: "STH/Technology and Health" },
    { code: "HLA", name: "STH/Environmental Physiology" },
    { code: "HLF", name: "STH/Basic Science" },
    { code: "HLK", name: "STH/Neuronic" },
    { code: "HLL", name: "STH/Medical Technology" },
    { code: "HLM", name: "STH/Structural Biotechnology" },
    { code: "HPC", name: "STH/System Safety and Management" },
    { code: "HPCA", name: "STH/Technology in Health Care" },
    { code: "HPE", name: "STH/Unit for Health Innovation" },
    { code: "HPG", name: "STH/DASH" },
    { code: "HPM", name: "STH/Health Care Logistics" },
    { code: "HPN", name: "STH/Ergonomics" },
    { code: "HSE", name: "STH/Computer and Electrical Engineering" },
    { code: "HSL", name: "STH/Medical Imaging" },
    { code: "HSM", name: "STH/Medical Imaging and Visualization" },
    { code: "HSN", name: "STH/Neuronic Engineering" },
    { code: "IA", name: "ICT/Information and Communication Technology" },
    { code: "IE", name: "ICT/Electronic Systems" },
    { code: "IF", name: "ICT/Communications Systems" },
    { code: "IG", name: "ICT/Electronics" },
    { code: "IK", name: "ICT/Software and Computer system" },
    { code: "JF", name: "EECS/Communication" },
    { code: "JG", name: "EECS/Electronics and Embedded Systems" },
    { code: "JH", name: "EECS/Computer Science" },
    { code: "JHF", name: "EECS/Communication Systems" },
    { code: "JHK", name: "EECS/Software and Computer Systems" },
    { code: "JHP", name: "EECS/Network and Systems Engineering" },
    { code: "JHS", name: "EECS/Computational Science and  Technology" },
    { code: "JHT", name: "EECS/Theoretical Computer Science" },
    { code: "JJ", name: "EECS/Electrical Engineering" },
    { code: "JJD", name: "EECS/Fusion Plasma Physics" },
    { code: "JJE", name: "EECS/Space and Plasma Physics" },
    { code: "JJG", name: "EECS/Electronics and Embedded Systems" },
    { code: "JJI", name: "EECS/Electromagnetic Engineering" },
    { code: "JJN", name: "EECS/Electric Power and Energy Systems" },
    { code: "JM", name: "EECS/Human Centered Technology" },
    { code: "JMA", name: "EECS/Media Technology and Interaction Design" },
    { code: "JR", name: "EECS/Intelligent Systems" },
    { code: "JRL", name: "EECS/Decision and Control Systems" },
    { code: "JRO", name: "EECS/Information Science and Engineering" },
    { code: "JRQ", name: "EECS/Micro and Nano Systems" },
    { code: "JRR", name: "EECS/Robotics, Perception and Learning" },
    { code: "JRT", name: "EECS/Speech, Music and Hearing" },
    { code: "KA", name: "CHE/Chemical Science and Engineering" },
    { code: "KD", name: "CHE/Chemistry" },
    { code: "KE", name: "CHE/Chemical Engineering and Technology" },
    { code: "KET", name: "CHE/Chemical Technology" },
    { code: "KF", name: "CHE/Fibre and Polymer Technology" },
    { code: "KH", name: "CHE/Engineering Pedagogics" },
    { code: "KHB", name: "CHE/Degree progr in Chemical Engineering" },
    { code: "KHD", name: "CHE/Technical Preperatory Year" },
    { code: "L", name: "ECE/School of Education and Communication" },
    { code: "LAC", name: "ECE/Student Administration Office" },
    { code: "LGC", name: "ECE/Library" },
    { code: "LJ", name: "ECE/Learning Lab" },
    { code: "LP", name: "ECE/Learning" },
    { code: "LPA", name: "ECE/Teacher Education" },
    { code: "LPB", name: "ECE/Teaching and Learning" },
    { code: "LS", name: "ECE/Language and Communication" },
    {
        code: "MAC",
        name: "ITM/School of Industrial Engineering and Management",
    },
    { code: "MD", name: "ITM/Energy Technology" },
    { code: "ME", name: "ITM/Industrial Economics and Management" },
    { code: "MF", name: "ITM/Machine Design" },
    { code: "MG", name: "ITM/Production Engineering" },
    { code: "MH", name: "ITM/Materials Science and Engineering" },
    { code: "MJ", name: "ITM/Energy Technology" },
    { code: "MJEA", name: "ITM/Energy Technology" },
    { code: "MJEC", name: "ITM/Heat and Power Technology" },
    { code: "ML", name: "ITM/Sustainable Production Development" },
    { code: "MO", name: "ITM/Learning in Engineering Sciences" },
    { code: "MV", name: "ITM/Materials Science and Engineering" },
    { code: "SA", name: "SCI/Engineering Sciences" },
    { code: "SD", name: "SCI/Aeronautical and Vehicle Engineering" },
    { code: "SE", name: "SCI/Solid Mechanics" },
    { code: "SF", name: "SCI/Mathematics" },
    { code: "SG", name: "SCI/Mechanics" },
    { code: "SH", name: "SCI/Physics" },
    { code: "SHB", name: "SCI/Undergraduate Physics" },
    { code: "SI", name: "SCI/Theoretical Physics" },
    { code: "SIB", name: "SCI/Theoretical Undergaduate Physics" },
    { code: "SK", name: "SCI/Applied Physics" },
    { code: "SKB", name: "SCI/Applied undergraduate Physics" },
    { code: "SM", name: "SCI/Engineering Mechanics" },
    { code: "UL", name: "Stockholm University" },
    { code: "VDVC", name: "KTH University Administration" },
]

const schools = [
    {
        code: "ABE",
        name: "ABE/Architecture and the Built Environment",
        orgUnit: "A",
    },
    { code: "STH", name: "STH/Technology and Health", orgUnit: "H" },
    {
        code: "ITM",
        name: "ITM/Industrial Engineering and Management",
        orgUnit: "M",
    },
    { code: "BIO", name: "BIO/Biotechnology", orgUnit: "B" },
    {
        code: "CSC",
        name: "CSC/Computer Science and Communication",
        orgUnit: "D",
    },
    { code: "EES", name: "EES/Electrical Engineering", orgUnit: "E" },
    { code: "CHE", name: "CHE/Chemical Science and Engineering", orgUnit: "K" },
    {
        code: "ICT",
        name: "ICT/Information and Communication Technology",
        orgUnit: "I",
    },
    {
        code: "XXX",
        name: "XXX/Cooperation with other universities",
        orgUnit: "U",
    },
    {
        code: "ECE",
        name: "ECE/Education and Communication in Engineering Science",
        orgUnit: "L",
    },
    { code: "SCI", name: "SCI/Engineering Sciences", orgUnit: "S" },
    {
        code: "CBH",
        name: "CBH/Engineering Sciences in Chemistry, Biotechnology and Health",
        orgUnit: "C",
    },
    {
        code: "EECS",
        name: "EECS/Electrical Engineering and Computer Science",
        orgUnit: "J",
    },
]

export { schools, departments }
