const universities = [
    {
        "ranking": 1,
        "title": "University of Oxford",
        "location": "United Kingdom",
        "number students": "20,774",
        "students staff ratio": "11.1",
        "perc intl students": "41%",
        "gender ratio": "46 : 54",
    },
    {
        "ranking": 2,
        "title": "Stanford University",
        "location": "United States",
        "number students": "16,223",
        "students staff ratio": "7.4",
        "perc intl students": "23%",
        "gender ratio": "44 : 56",
    },
    {
        "ranking": 3,
        "title": "Harvard University",
        "location": "United States",
        "number students": "21,261",
        "students staff ratio": "9.3",
        "perc intl students": "25%",
        "gender ratio": "49 : 51",
    },
    {
        "ranking": 4,
        "title": "California Institute of Technology",
        "location": "United States",
        "number students": "2,238",
        "students staff ratio": "6.3",
        "perc intl students": "33%",
        "gender ratio": "36 : 64",
    },
    {
        "ranking": 5,
        "title": "Massachusetts Institute of Technology",
        "location": "United States",
        "number students": "11,276",
        "students staff ratio": "8.4",
        "perc intl students": "34%",
        "gender ratio": "39 : 61",
    },
    {
        "ranking": 6,
        "title": "University of Cambridge",
        "location": "United Kingdom",
        "number students": "19,370",
        "students staff ratio": "11.0",
        "perc intl students": "38%",
        "gender ratio": "47 : 53",
    },
    {
        "ranking": 7,
        "title": "University of California, Berkeley",
        "location": "United States",
        "number students": "39,918",
        "students staff ratio": "19.8",
        "perc intl students": "17%",
        "gender ratio": "51 : 49",
    },
    {
        "ranking": 8,
        "title": "Yale University",
        "location": "United States",
        "number students": "12,910",
        "students staff ratio": "6.0",
        "perc intl students": "20%",
        "gender ratio": "50 : 50",
    },
    {
        "ranking": 9,
        "title": "Princeton University",
        "location": "United States",
        "number students": "8,091",
        "students staff ratio": "8.0",
        "perc intl students": "23%",
        "gender ratio": "46 : 54",
    },
    {
        "ranking": 10,
        "title": "The University of Chicago",
        "location": "United States",
        "number students": "14,292",
        "students staff ratio": "5.9",
        "perc intl students": "31%",
        "gender ratio": "46 : 54",
    },
    {
        "ranking": 11,
        "title": "Imperial College London",
        "location": "United Kingdom",
        "number students": "17,176",
        "students staff ratio": "11.6",
        "perc intl students": "58%",
        "gender ratio": "39 : 61",
    },
    {
        "ranking": 12,
        "title": "Johns Hopkins University",
        "location": "United States",
        "number students": "16,432",
        "students staff ratio": "4.4",
        "perc intl students": "27%",
        "gender ratio": "52 : 48",
    },
    {
        "ranking": 13,
        "title": "University of Pennsylvania",
        "location": "United States",
        "number students": "20,771",
        "students staff ratio": "6.4",
        "perc intl students": "21%",
        "gender ratio": "52 : 48",
    },
    {
        "ranking": 14,
        "title": "ETH Zurich",
        "location": "Switzerland",
        "number students": "19,632",
        "students staff ratio": "13.1",
        "perc intl students": "40%",
        "gender ratio": "32 : 68",
    },
    {
        "ranking": 15,
        "title": "University of California, Los Angeles",
        "location": "United States",
        "number students": "41,673",
        "students staff ratio": "10.0",
        "perc intl students": "17%",
        "gender ratio": "55 : 45",
    },
    {
        "ranking": 16,
        "title": "UCL",
        "location": "United Kingdom",
        "number students": "34,590",
        "students staff ratio": "10.8",
        "perc intl students": "55%",
        "gender ratio": "57 : 43",
    },
    {
        "ranking": 17,
        "title": "Columbia University",
        "location": "United States",
        "number students": "27,384",
        "students staff ratio": "5.7",
        "perc intl students": "39%",
        "gender ratio": "n/a",
    },
    {
        "ranking": 18,
        "title": "University of Toronto",
        "location": "Canada",
        "number students": "74,502",
        "students staff ratio": "20.0",
        "perc intl students": "22%",
        "gender ratio": "59 : 41",
    },
    {
        "ranking": 19,
        "title": "Cornell University",
        "location": "United States",
        "number students": "23,016",
        "students staff ratio": "10.2",
        "perc intl students": "25%",
        "gender ratio": "50 : 50",
    },
    {
        "ranking": 20,
        "title": "Duke University",
        "location": "United States",
        "number students": "15,489",
        "students staff ratio": "4.3",
        "perc intl students": "21%",
        "gender ratio": "49 : 51",
    },
    {
        "ranking": 21,
        "title": "Tsinghua University",
        "location": "China",
        "number students": "37,484",
        "students staff ratio": "11.6",
        "perc intl students": "13%",
        "gender ratio": "34 : 66",
    },
    {
        "ranking": 22,
        "title": "University of Michigan-Ann Arbor",
        "location": "United States",
        "number students": "43,873",
        "students staff ratio": "8.3",
        "perc intl students": "17%",
        "gender ratio": "50 : 50",
    },
    {
        "ranking": 23,
        "title": "Peking University",
        "location": "China",
        "number students": "38,583",
        "students staff ratio": "11.1",
        "perc intl students": "16%",
        "gender ratio": "43 : 57",
    },
    {
        "ranking": 24,
        "title": "Northwestern University",
        "location": "United States",
        "number students": "18,529",
        "students staff ratio": "13.0",
        "perc intl students": "19%",
        "gender ratio": "49 : 51",
    },
    {
        "ranking": 25,
        "title": "National University of Singapore",
        "location": "Singapore",
        "number students": "30,943",
        "students staff ratio": "18.0",
        "perc intl students": "26%",
        "gender ratio": "50 : 50",
    },
    {
        "ranking": 26,
        "title": "New York University",
        "location": "United States",
        "number students": "44,474",
        "students staff ratio": "8.8",
        "perc intl students": "34%",
        "gender ratio": "57 : 43",
    },
    {
        "ranking": 27,
        "title": "London School of Economics and Political Science",
        "location": "United Kingdom",
        "number students": "10,660",
        "students staff ratio": "12.0",
        "perc intl students": "72%",
        "gender ratio": "54 : 46",
    },
    {
        "ranking": 28,
        "title": "Carnegie Mellon University",
        "location": "United States",
        "number students": "14,058",
        "students staff ratio": "13.7",
        "perc intl students": "48%",
        "gender ratio": "43 : 57",
    },
    {
        "ranking": 29,
        "title": "University of Washington",
        "location": "United States",
        "number students": "46,258",
        "students staff ratio": "10.7",
        "perc intl students": "17%",
        "gender ratio": "53 : 47",
    },
    {
        "ranking": 30,
        "title": "University of Edinburgh",
        "location": "United Kingdom",
        "number students": "30,649",
        "students staff ratio": "12.1",
        "perc intl students": "42%",
        "gender ratio": "60 : 40",
    },
    {
        "ranking": 31,
        "title": "University of Melbourne",
        "location": "Australia",
        "number students": "50,094",
        "students staff ratio": "27.0",
        "perc intl students": "48%",
        "gender ratio": "57 : 43",
    },
    {
        "ranking": 32,
        "title": "LMU Munich",
        "location": "Germany",
        "number students": "34,249",
        "students staff ratio": "33.6",
        "perc intl students": "17%",
        "gender ratio": "61 : 39",
    },
    {
        "ranking": 33,
        "title": "University of California, San Diego",
        "location": "United States",
        "number students": "34,232",
        "students staff ratio": "12.0",
        "perc intl students": "30%",
        "gender ratio": "47 : 53",
    },
    {
        "ranking": 34,
        "title": "University of British Columbia",
        "location": "Canada",
        "number students": "53,123",
        "students staff ratio": "18.7",
        "perc intl students": "32%",
        "gender ratio": "55 : 45",
    },
    {
        "ranking": 35,
        "title": "King\u2019s College London",
        "location": "United Kingdom",
        "number students": "27,400",
        "students staff ratio": "12.4",
        "perc intl students": "46%",
        "gender ratio": "62 : 38",
    },
    {
        "ranking": 36,
        "title": "Karolinska Institute",
        "location": "Sweden",
        "number students": "7,696",
        "students staff ratio": "8.8",
        "perc intl students": "26%",
        "gender ratio": "68 : 32",
    },
    {
        "ranking": 37,
        "title": "The University of Tokyo",
        "location": "Japan",
        "number students": "25,935",
        "students staff ratio": "10.6",
        "perc intl students": "13%",
        "gender ratio": "n/a",
    },
    {
        "ranking": 38,
        "title": "Georgia Institute of Technology",
        "location": "United States",
        "number students": "26,043",
        "students staff ratio": "23.6",
        "perc intl students": "27%",
        "gender ratio": "33 : 67",
    },
    {
        "ranking": 39,
        "title": "University of Hong Kong",
        "location": "Hong Kong",
        "number students": "18,135",
        "students staff ratio": "18.2",
        "perc intl students": "43%",
        "gender ratio": "54 : 46",
    },
    {
        "ranking": 40,
        "title": "McGill University",
        "location": "Canada",
        "number students": "31,578",
        "students staff ratio": "12.8",
        "perc intl students": "31%",
        "gender ratio": "59 : 41",
    },
    {
        "ranking": 41,
        "title": "Technical University of Munich",
        "location": "Germany",
        "number students": "32,377",
        "students staff ratio": "39.8",
        "perc intl students": "31%",
        "gender ratio": "36 : 64",
    },
    {
        "ranking": 42,
        "title": "Heidelberg University",
        "location": "Germany",
        "number students": "20,020",
        "students staff ratio": "14.5",
        "perc intl students": "18%",
        "gender ratio": "54 : 46",
    },
    {
        "ranking": 43,
        "title": "\u00c9cole Polytechnique F\u00e9d\u00e9rale de Lausanne",
        "location": "Switzerland",
        "number students": "10,942",
        "students staff ratio": "12.2",
        "perc intl students": "60%",
        "gender ratio": "29 : 71",
    },
    {
        "ranking": 44,
        "title": "University of Texas at Austin",
        "location": "United States",
        "number students": "49,510",
        "students staff ratio": "16.9",
        "perc intl students": "10%",
        "gender ratio": "52 : 48",
    },
    {
        "ranking": 45,
        "title": "KU Leuven",
        "location": "Belgium",
        "number students": "45,617",
        "students staff ratio": "36.1",
        "perc intl students": "15%",
        "gender ratio": "50 : 50",
    },
    {
        "ranking": 46,
        "title":
            "Paris Sciences et Lettres \u2013 PSL Research University Paris",
        "location": "France",
        "number students": "20,701",
        "students staff ratio": "14.7",
        "perc intl students": "24%",
        "gender ratio": "46 : 54",
    },
    {
        "ranking": 47,
        "title": "Nanyang Technological University, Singapore",
        "location": "Singapore",
        "number students": "23,902",
        "students staff ratio": "14.8",
        "perc intl students": "25%",
        "gender ratio": "48 : 52",
    },
    {
        "ranking": 48,
        "title": "University of Illinois at Urbana-Champaign",
        "location": "United States",
        "number students": "45,980",
        "students staff ratio": "17.8",
        "perc intl students": "24%",
        "gender ratio": "48 : 52",
    },
    {
        "ranking": 49,
        "title": "University of Wisconsin-Madison",
        "location": "United States",
        "number students": "39,451",
        "students staff ratio": "9.8",
        "perc intl students": "13%",
        "gender ratio": "n/a",
    },
    {
        "ranking": 50,
        "title": "Washington University in St Louis",
        "location": "United States",
        "number students": "13,693",
        "students staff ratio": "7.5",
        "perc intl students": "21%",
        "gender ratio": "n/a",
    },
    {
        "ranking": 51,
        "title": "University of Manchester",
        "location": "United Kingdom",
        "number students": "36,557",
        "students staff ratio": "14.4",
        "perc intl students": "41%",
        "gender ratio": "53 : 47",
    },
    {
        "ranking": 52,
        "title": "University of Sydney",
        "location": "Australia",
        "number students": "46,453",
        "students staff ratio": "19.4",
        "perc intl students": "43%",
        "gender ratio": "58 : 42",
    },
    {
        "ranking": 53,
        "title": "University of Southern California",
        "location": "United States",
        "number students": "41,953",
        "students staff ratio": "13.0",
        "perc intl students": "23%",
        "gender ratio": "49 : 51",
    },
    {
        "ranking": 54,
        "title": "Boston University",
        "location": "United States",
        "number students": "26,510",
        "students staff ratio": "11.1",
        "perc intl students": "28%",
        "gender ratio": "59 : 41",
    },
    {
        "ranking": 55,
        "title": "Kyoto University",
        "location": "Japan",
        "number students": "22,935",
        "students staff ratio": "9.3",
        "perc intl students": "11%",
        "gender ratio": "25 : 75",
    },
    {
        "ranking": 56,
        "title": "Chinese University of Hong Kong",
        "location": "Hong Kong",
        "number students": "18,675",
        "students staff ratio": "19.3",
        "perc intl students": "33%",
        "gender ratio": "n/a",
    },
    {
        "ranking": 57,
        "title": "The Hong Kong University of Science and Technology",
        "location": "Hong Kong",
        "number students": "9,976",
        "students staff ratio": "21.6",
        "perc intl students": "30%",
        "gender ratio": "n/a",
    },
    {
        "ranking": 58,
        "title": "University of North Carolina at Chapel Hill",
        "location": "United States",
        "number students": "30,956",
        "students staff ratio": "8.2",
        "perc intl students": "8%",
        "gender ratio": "58 : 42",
    },
    {
        "ranking": 59,
        "title": "Australian National University",
        "location": "Australia",
        "number students": "18,801",
        "students staff ratio": "17.8",
        "perc intl students": "47%",
        "gender ratio": "53 : 47",
    },
    {
        "ranking": 60,
        "title": "Seoul National University",
        "location": "South Korea",
        "number students": "26,757",
        "students staff ratio": "15.1",
        "perc intl students": "11%",
        "gender ratio": "n/a",
    },
    {
        "ranking": 61,
        "title": "Brown University",
        "location": "United States",
        "number students": "9,695",
        "students staff ratio": "10.8",
        "perc intl students": "20%",
        "gender ratio": "n/a",
    },
    {
        "ranking": 62,
        "title": "The University of Queensland",
        "location": "Australia",
        "number students": "40,389",
        "students staff ratio": "35.5",
        "perc intl students": "38%",
        "gender ratio": "55 : 45",
    },
    {
        "ranking": 63,
        "title": "Wageningen University & Research",
        "location": "Netherlands",
        "number students": "14,356",
        "students staff ratio": "21.0",
        "perc intl students": "27%",
        "gender ratio": "54 : 46",
    },
    {
        "ranking": 64,
        "title": "University of California, Davis",
        "location": "United States",
        "number students": "36,395",
        "students staff ratio": "13.6",
        "perc intl students": "17%",
        "gender ratio": "58 : 42",
    },
    {
        "ranking": 65,
        "title": "Monash University",
        "location": "Australia",
        "number students": "57,406",
        "students staff ratio": "41.7",
        "perc intl students": "43%",
        "gender ratio": "57 : 43",
    },
    {
        "ranking": 66,
        "title": "University of Amsterdam",
        "location": "Netherlands",
        "number students": "24,747",
        "students staff ratio": "12.8",
        "perc intl students": "24%",
        "gender ratio": "57 : 43",
    },
    {
        "ranking": 67,
        "title": "UNSW Sydney",
        "location": "Australia",
        "number students": "46,234",
        "students staff ratio": "41.0",
        "perc intl students": "44%",
        "gender ratio": "47 : 53",
    },
    {
        "ranking": 68,
        "title": "University of California, Santa Barbara",
        "location": "United States",
        "number students": "24,780",
        "students staff ratio": "28.2",
        "perc intl students": "18%",
        "gender ratio": "53 : 47",
    },
    {
        "ranking": 69,
        "title": "McMaster University",
        "location": "Canada",
        "number students": "25,285",
        "students staff ratio": "30.5",
        "perc intl students": "18%",
        "gender ratio": "55 : 45",
    },
    {
        "ranking": 70,
        "title": "Fudan University",
        "location": "China",
        "number students": "32,597",
        "students staff ratio": "11.2",
        "perc intl students": "13%",
        "gender ratio": "52 : 48",
    },
    {
        "ranking": 71,
        "title": "Leiden University",
        "location": "Netherlands",
        "number students": "30,178",
        "students staff ratio": "19.0",
        "perc intl students": "18%",
        "gender ratio": "59 : 41",
    },
    {
        "ranking": 72,
        "title": "Erasmus University Rotterdam",
        "location": "Netherlands",
        "number students": "26,453",
        "students staff ratio": "26.8",
        "perc intl students": "22%",
        "gender ratio": "50 : 50",
    },
    {
        "ranking": 73,
        "title": "University of Montreal",
        "location": "Canada",
        "number students": "36,774",
        "students staff ratio": "20.2",
        "perc intl students": "21%",
        "gender ratio": "n/a",
    },
    {
        "ranking": 74,
        "title": "University of Zurich",
        "location": "Switzerland",
        "number students": "22,960",
        "students staff ratio": "14.8",
        "perc intl students": "21%",
        "gender ratio": "57 : 43",
    },
    {
        "ranking": 75,
        "title": "Charit\u00e9 - Universit\u00e4tsmedizin Berlin",
        "location": "Germany",
        "number students": "7,431",
        "students staff ratio": "17.4",
        "perc intl students": "20%",
        "gender ratio": "65 : 35",
    },
    {
        "ranking": 76,
        "title": "Utrecht University",
        "location": "Netherlands",
        "number students": "32,022",
        "students staff ratio": "14.0",
        "perc intl students": "10%",
        "gender ratio": "58 : 42",
    },
    {
        "ranking": 77,
        "title": "University of Warwick",
        "location": "United Kingdom",
        "number students": "21,777",
        "students staff ratio": "13.3",
        "perc intl students": "41%",
        "gender ratio": "49 : 51",
    },
    {
        "ranking": 78,
        "title": "Delft University of Technology",
        "location": "Netherlands",
        "number students": "19,594",
        "students staff ratio": "17.4",
        "perc intl students": "31%",
        "gender ratio": "30 : 70",
    },
    {
        "ranking": 79,
        "title": "University of T\u00fcbingen",
        "location": "Germany",
        "number students": "27,590",
        "students staff ratio": "36.6",
        "perc intl students": "14%",
        "gender ratio": "58 : 42",
    },
    {
        "ranking": 80,
        "title": "University of Groningen",
        "location": "Netherlands",
        "number students": "28,392",
        "students staff ratio": "23.9",
        "perc intl students": "23%",
        "gender ratio": "51 : 49",
    },
    {
        "ranking": 81,
        "title": "Humboldt University of Berlin",
        "location": "Germany",
        "number students": "33,388",
        "students staff ratio": "56.3",
        "perc intl students": "18%",
        "gender ratio": "n/a",
    },
    {
        "ranking": 82,
        "title": "Ohio State University (Main campus)",
        "location": "United States",
        "number students": "54,650",
        "students staff ratio": "12.1",
        "perc intl students": "13%",
        "gender ratio": "50 : 50",
    },
    {
        "ranking": 83,
        "title": "University of Freiburg",
        "location": "Germany",
        "number students": "14,878",
        "students staff ratio": "32.5",
        "perc intl students": "21%",
        "gender ratio": "54 : 46",
    },
    {
        "ranking": 84,
        "title": "University of Copenhagen",
        "location": "Denmark",
        "number students": "30,746",
        "students staff ratio": "4.2",
        "perc intl students": "17%",
        "gender ratio": "62 : 38",
    },
    {
        "ranking": 85,
        "title": "Emory University",
        "location": "United States",
        "number students": "12,923",
        "students staff ratio": "4.0",
        "perc intl students": "20%",
        "gender ratio": "59 : 41",
    },
    {
        "ranking": 86,
        "title": "University of Minnesota",
        "location": "United States",
        "number students": "61,994",
        "students staff ratio": "12.4",
        "perc intl students": "11%",
        "gender ratio": "53 : 47",
    },
    {
        "ranking": 87,
        "title": "\u00c9cole Polytechnique",
        "location": "France",
        "number students": "2,850",
        "students staff ratio": "5.6",
        "perc intl students": "44%",
        "gender ratio": "23 : 77",
    },
    {
        "ranking": 88,
        "title": "University of Science and Technology of China",
        "location": "China",
        "number students": "16,434",
        "students staff ratio": "7.2",
        "perc intl students": "5%",
        "gender ratio": "n/a",
    },
    {
        "ranking": 89,
        "title": "Sorbonne University",
        "location": "France",
        "number students": "43,585",
        "students staff ratio": "12.8",
        "perc intl students": "20%",
        "gender ratio": "58 : 42",
    },
    {
        "ranking": 90,
        "title": "University of Maryland, College Park",
        "location": "United States",
        "number students": "33,671",
        "students staff ratio": "16.6",
        "perc intl students": "11%",
        "gender ratio": "48 : 52",
    },
    {
        "ranking": 91,
        "title": "University of Bristol",
        "location": "United Kingdom",
        "number students": "22,981",
        "students staff ratio": "14.5",
        "perc intl students": "28%",
        "gender ratio": "55 : 45",
    },
    {
        "ranking": 92,
        "title": "University of Basel",
        "location": "Switzerland",
        "number students": "9,229",
        "students staff ratio": "12.3",
        "perc intl students": "30%",
        "gender ratio": "55 : 45",
    },
    {
        "ranking": 93,
        "title": "University of Glasgow",
        "location": "United Kingdom",
        "number students": "26,533",
        "students staff ratio": "14.7",
        "perc intl students": "38%",
        "gender ratio": "59 : 41",
    },
    {
        "ranking": 94,
        "title": "Purdue University West Lafayette",
        "location": "United States",
        "number students": "41,573",
        "students staff ratio": "16.3",
        "perc intl students": "22%",
        "gender ratio": "43 : 57",
    },
    {
        "ranking": 95,
        "title": "Zhejiang University",
        "location": "China",
        "number students": "33,825",
        "students staff ratio": "10.8",
        "perc intl students": "23%",
        "gender ratio": "23 : 77",
    },
    {
        "ranking": 96,
        "title": "Korea Advanced Institute of Science and Technology (KAIST)",
        "location": "South Korea",
        "number students": "9,514",
        "students staff ratio": "10.4",
        "perc intl students": "9%",
        "gender ratio": "20 : 80",
    },
    {
        "ranking": 97,
        "title": "National Taiwan University (NTU)",
        "location": "Taiwan",
        "number students": "24,880",
        "students staff ratio": "9.9",
        "perc intl students": "12%",
        "gender ratio": "43 : 57",
    },
    {
        "ranking": 98,
        "title": "University of California, Irvine",
        "location": "United States",
        "number students": "35,040",
        "students staff ratio": "17.5",
        "perc intl students": "27%",
        "gender ratio": "52 : 48",
    },
    {
        "ranking": 99,
        "title": "University of Helsinki",
        "location": "Finland",
        "number students": "22,137",
        "students staff ratio": "15.9",
        "perc intl students": "5%",
        "gender ratio": "66 : 34",
    },
    {
        "ranking": 100,
        "title": "Shanghai Jiao Tong University",
        "location": "China",
        "number students": "38,556",
        "students staff ratio": "11.9",
        "perc intl students": "11%",
        "gender ratio": "39 : 61",
    },
]

export { universities }
